# MTA On-Time Performance EDA

## Data Dictionary:
- https://data.ny.gov/Transportation/MTA-Subway-Terminal-On-Time-Performance-2015-2019/f6rf-2a3t/about_data
- https://data.ny.gov/Transportation/MTA-Subway-Terminal-On-Time-Performance-2020-2024/vtvh-gimj/about_data

In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

mta_time_1 = pd.read_csv('../data/MTA_Subway_Terminal_On-Time_Performance_2015-2019.csv', low_memory=False)
mta_time_2 = pd.read_csv('../data/MTA_Subway_Terminal_On-Time_Performance_2020-2024.csv', low_memory=False)

mta_time_1.head()

,month,division,line,day_type,num_on_time_trips,num_sched_trips,terminal_on_time_performance
0,2015-01-01,A DIVISION,1,1,"6,874","9,017",76.2337806%
1,2015-01-01,A DIVISION,2,1,"2,920","6,175",47.2874494%
2,2015-01-01,A DIVISION,3,1,"4,004","5,834",68.6321563%
3,2015-01-01,A DIVISION,4,1,"3,692","7,623",48.4323757%
4,2015-01-01,A DIVISION,5,1,"3,203","6,491",49.3452473%

In [2]:
mta_time_2.head()

,month,division,line,day_type,num_on_time_trips,num_sched_trips,terminal_on_time_performance
0,2024-12-01,A DIVISION,1,1,"7,689","9,711",79.17825%
1,2024-12-01,A DIVISION,1,2,"2,907","3,240",89.72222%
2,2024-12-01,A DIVISION,2,1,"4,693","6,997",67.071605%
3,2024-12-01,A DIVISION,2,2,"1,772","2,690",65.873605%
4,2024-12-01,A DIVISION,3,2,"1,389","1,710",81.22807%

In [3]:
mta_time_1.shape

(1596, 7)

In [6]:
mta_time_2.shape

(2686, 7)

In [7]:
mta_time_1[10:20]

,month,division,line,day_type,num_on_time_trips,num_sched_trips,terminal_on_time_performance
10,2015-01-01,B DIVISION,C,1,"3,359","4,000",83.975%
11,2015-01-01,B DIVISION,D,1,"4,022","5,288",76.0590015%
12,2015-01-01,B DIVISION,E,1,"5,453","7,894",69.0777806%
13,2015-01-01,B DIVISION,F,1,"4,597","7,939",57.9040181%
14,2015-01-01,B DIVISION,G,1,"3,961","5,664",69.9329096%
15,2015-01-01,B DIVISION,JZ,1,"4,374","5,444",80.3453343%
16,2015-01-01,B DIVISION,L,1,"9,109","9,808",92.8731648%
17,2015-01-01,B DIVISION,M,1,"3,761","5,315",70.7619944%
18,2015-01-01,B DIVISION,N,1,"3,601","5,259",68.4730937%
19,2015-01-01,B DIVISION,Q,1,"3,737","5,348",69.8765894%

In [10]:
mta_time_df = pd.concat([mta_time_1, mta_time_2], ignore_index=True)

mta_time_df.shape

(4282, 7)

In [11]:
mta_time_df.sample(10)

,month,division,line,day_type,num_on_time_trips,num_sched_trips,terminal_on_time_performance
128,2015-06-01,B DIVISION,F,1,"5,033","8,374",60.1026988%
2405,2023-07-01,B DIVISION,R,2,"2,000","2,372",84.317034%
3260,2021-12-01,B DIVISION,R,2,"1,646","2,152",76.486987%
2282,2023-09-01,A DIVISION,6,2,"2,412","3,020",79.86755%
853,2018-01-01,B DIVISION,D,1,"4,994","11,892",41.9946182%
3240,2021-12-01,B DIVISION,F,1,"5,373","7,889",68.10749%
1813,2024-08-01,B DIVISION,M,1,"5,064","6,424",78.82939%
1595,2019-12-01,B DIVISION,S Rock,2,"1,497","1,544",96.9559585%
2294,2023-09-01,B DIVISION,F,1,"4,797","7,798",61.51577%
148,2015-07-01,B DIVISION,C,1,"3,407","4,400",77.4318182%

In [16]:
mta_time_df['line'].value_counts(sort=False)

line
1         189
2         189
3         189
4         189
5         189
6         189
7         189
S 42nd     77
A         188
B         118
C         187
D         189
E         189
F         189
G         189
JZ         77
L         189
M         189
N         189
Q         189
R         189
S Fkln     77
S Rock     77
W          18
FS        112
GS        103
H         112
J         112
Name: count, dtype: int64