# MTA Subway Stations EDA

## Data Dictionary:
- https://data.ny.gov/Transportation/MTA-Subway-Stations/39hk-dx4f/about_data

In [12]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

mta_data = pd.read_csv('../data/MTA_Subway_Stations_2025.csv', low_memory=False)

mta_data[150:175]

,GTFS Stop ID,Station ID,Complex ID,Division,Line,Stop Name,Borough,CBD,Daytime Routes,Structure,GTFS Latitude,GTFS Longitude,North Direction Label,South Direction Label,ADA,ADA Northbound,ADA Southbound,ADA Notes,Georeference
150,D13,151,151,IND,Concourse,145 St,M,False,B D,Subway,40.824783,-73.944216,Uptown,Downtown,0,0,0,NaN,POINT (-73.944216 40.824783)
151,A14,152,152,IND,8th Av - Fulton St,135 St,M,False,C B,Subway,40.817894,-73.947649,Uptown,Downtown,0,0,0,NaN,POINT (-73.947649 40.817894)
152,A15,153,153,IND,8th Av - Fulton St,125 St,M,False,A C B D,Subway,40.811109,-73.952343,Uptown,Downtown,1,1,1,NaN,POINT (-73.952343 40.811109)
153,A16,154,154,IND,8th Av - Fulton St,116 St,M,False,C B,Subway,40.805085,-73.954882,Uptown,Downtown,0,0,0,NaN,POINT (-73.954882 40.805085)
154,A17,155,155,IND,8th Av - Fulton St,Cathedral Pkwy (110 St),M,False,C B,Subway,40.800603,-73.958161,Uptown,Downtown,0,0,0,NaN,POINT (-73.958161 40.800603)
155,A18,156,156,IND,8th Av - Fulton St,103 St,M,False,C B,Subway,40.796092,-73.961454,Uptown,Downtown,0,0,0,NaN,POINT (-73.961454 40.796092)
156,A19,157,157,IND,8th Av - Fulton St,96 St,M,False,C B,Subway,40.791642,-73.964696,Uptown,Downtown,0,0,0,NaN,POINT (-73.964696 40.791642)
157,A20,158,158,IND,8th Av - Fulton St,86 St,M,False,C B,Subway,40.785868,-73.968916,Uptown,Downtown,0,0,0,NaN,POINT (-73.968916 40.785868)
158,A21,159,159,IND,8th Av - Fulton St,81 St-Museum of Natural History,M,False,C B,Subway,40.781433,-73.972143,Uptown,Downtown,0,0,0,NaN,POINT (-73.972143 40.781433)
159,A22,160,160,IND,8th Av - Fulton St,72 St,M,False,C B,Subway,40.775594,-73.976410,Uptown,Downtown,0,0,0,NaN,POINT (-73.97641 40.775594)
160,A24,161,614,IND,8th Av - Fulton St,59 St-Columbus Circle,M,True,A C B D,Subway,40.768296,-73.981736,Uptown,Downtown,1,1,1,NaN,POINT (-73.981736 40.768296)
161,A25,162,162,IND,8th Av - Fulton St,50 St,M,True,C E,Subway,40.762456,-73.985984,Uptown,Downtown,2,0,1,Downtown only,POINT (-73.985984 40.762456)
162,A27,163,611,IND,8th Av - Fulton St,42 St-Port Authority Bus Terminal,M,True,A C E,Subway,40.757308,-73.989735,Uptown,Downtown,1,1,1,NaN,POINT (-73.989735 40.757308)
163,A28,164,164,IND,8th Av - Fulton St,34 St-Penn Station,M,True,A C E,Subway,40.752287,-73.993391,Uptown,Downtown,1,1,1,NaN,POINT (-73.993391 40.752287)
164,A30,165,165,IND,8th Av - Fulton St,23 St,M,True,C E,Subway,40.745906,-73.998041,Uptown,Downtown,0,0,0,NaN,POINT (-73.998041 40.745906)
165,A31,166,618,IND,8th Av - Fulton St,14 St,M,True,A C E,Subway,40.740893,-74.001690,Uptown,Downtown,1,1,1,NaN,POINT (-74.00169 40.740893)
166,A32,167,167,IND,8th Av - Fulton St,W 4 St-Wash Sq,M,True,A C E,Subway,40.732338,-74.000495,Uptown,Downtown,1,1,1,NaN,POINT (-74.000495 40.732338)
167,D20,167,167,IND,6th Av - Culver,W 4 St-Wash Sq,M,True,B D F M,Subway,40.732338,-74.000495,Uptown,Downtown,1,1,1,NaN,POINT (-74.000495 40.732338)
168,A33,168,168,IND,8th Av - Fulton St,Spring St,M,True,C E,Subway,40.726227,-74.003739,Uptown,Downtown,2,0,1,Downtown only,POINT (-74.003739 40.726227)
169,A34,169,169,IND,8th Av - Fulton St,Canal St,M,True,A C E,Subway,40.720824,-74.005229,Uptown,Downtown,0,0,0,NaN,POINT (-74.005229 40.720824)
170,A36,170,624,IND,8th Av - Fulton St,Chambers St,M,True,A C,Subway,40.714111,-74.008585,Uptown,Brooklyn,0,0,0,NaN,POINT (-74.008585 40.714111)
171,E01,171,624,IND,8th Av - Fulton St,World Trade Center,M,True,E,Subway,40.712582,-74.009781,Uptown,Last Stop,1,1,1,NaN,POINT (-74.009781 40.712582)
172,A38,172,628,IND,8th Av - Fulton St,Fulton St,M,True,A C,Subway,40.710197,-74.007691,Uptown,Brooklyn,1,1,1,NaN,POINT (-74.007691 40.710197)
173,A40,173,173,IND,8th Av - Fulton St,High St,Bk,False,A C,Subway,40.699337,-73.990531,Manhattan,Outbound,0,0,0,NaN,POINT (-73.990531 40.699337)
174,A41,174,636,IND,8th Av - Fulton St,Jay St-MetroTech,Bk,False,A C F,Subway,40.692338,-73.987342,Manhattan,Outbound,1,1,1,NaN,POINT (-73.987342 40.692338)

In [13]:
mta_data.shape

(496, 19)

In [14]:
mta_data['GTFS Stop ID'].is_unique

True

In [15]:
mta_data['Station ID'].nunique()

493

## Note:
- three (3) duplicate Station ID numbers exist:
- 151, 167, 461
- Are of no concern considering 'GTFS Stop ID's are unique *

In [16]:
dup_ids = mta_data[mta_data['Station ID'].duplicated(keep=False)]  # Get all occurrences of duplicates
dup_ids

,GTFS Stop ID,Station ID,Complex ID,Division,Line,Stop Name,Borough,CBD,Daytime Routes,Structure,GTFS Latitude,GTFS Longitude,North Direction Label,South Direction Label,ADA,ADA Northbound,ADA Southbound,ADA Notes,Georeference
149,A12,151,151,IND,8th Av - Fulton St,145 St,M,False,A C,Subway,40.824783,-73.944216,Uptown,Downtown,0,0,0,NaN,POINT (-73.944216 40.824783)
150,D13,151,151,IND,Concourse,145 St,M,False,B D,Subway,40.824783,-73.944216,Uptown,Downtown,0,0,0,NaN,POINT (-73.944216 40.824783)
166,A32,167,167,IND,8th Av - Fulton St,W 4 St-Wash Sq,M,True,A C E,Subway,40.732338,-74.000495,Uptown,Downtown,1,1,1,NaN,POINT (-74.000495 40.732338)
167,D20,167,167,IND,6th Av - Culver,W 4 St-Wash Sq,M,True,B D F M,Subway,40.732338,-74.000495,Uptown,Downtown,1,1,1,NaN,POINT (-74.000495 40.732338)
461,R09,461,461,BMT,Astoria,Queensboro Plaza,Q,False,N W,Elevated,40.750582,-73.940202,Astoria,Manhattan,1,1,1,NaN,POINT (-73.940202 40.750582)
462,718,461,461,IRT,Flushing,Queensboro Plaza,Q,False,7,Elevated,40.750582,-73.940202,Outbound,Manhattan,1,1,1,NaN,POINT (-73.940202 40.750582)

# Approach:
- Use Latitude and Longitude to group stations to their respective Zip Codes and Census Tracts (Community District requires an API or another library, handle this later)
- Zip code not already present; must input using us_zip_codes.csv

In [17]:
from scipy.spatial import KDTree

# Finding each MTA station's zip code using KDTree:
zips = pd.read_csv('../data/us_zip_codes.csv')
zips_ny = zips[zips['state_id'] == 'NY']
tree = KDTree(zips_ny[['lat', 'lng']].values)

distances, indices = tree.query(mta_data[['GTFS Latitude', 'GTFS Longitude']].values)
mta_data['zip_code'] = zips_ny.iloc[indices]['zip'].values

mta_data.head()

,GTFS Stop ID,Station ID,Complex ID,Division,Line,Stop Name,Borough,CBD,Daytime Routes,Structure,GTFS Latitude,GTFS Longitude,North Direction Label,South Direction Label,ADA,ADA Northbound,ADA Southbound,ADA Notes,Georeference,zip_code
0,R01,1,1,BMT,Astoria,Astoria-Ditmars Blvd,Q,False,N W,Elevated,40.775036,-73.912034,Last Stop,Manhattan,0,0,0,NaN,POINT (-73.912034 40.775036),11105
1,R03,2,2,BMT,Astoria,Astoria Blvd,Q,False,N W,Elevated,40.770258,-73.917843,Astoria,Manhattan,1,1,1,NaN,POINT (-73.917843 40.770258),11102
2,R04,3,3,BMT,Astoria,30 Av,Q,False,N W,Elevated,40.766779,-73.921479,Astoria,Manhattan,0,0,0,NaN,POINT (-73.921479 40.766779),11102
3,R05,4,4,BMT,Astoria,Broadway,Q,False,N W,Elevated,40.761820,-73.925508,Astoria,Manhattan,0,0,0,NaN,POINT (-73.925508 40.76182),11106
4,R06,5,5,BMT,Astoria,36 Av,Q,False,N W,Elevated,40.756804,-73.929575,Astoria,Manhattan,0,0,0,NaN,POINT (-73.929575 40.756804),11106

In [18]:
import censusgeocode as cg


# If code fails, try forcing urllib3 back to the version that still included the appengine module:
# Either run this in your terminal, or uncomment the line below and run it in your notebook:
# !pip install "urllib3<2"

def get_census_tract(lat, lon):
    try:
        # Note: Census API uses x=longitude, y=latitude
        result = cg.coordinates(x=lon, y=lat)
        
        if result and 'Census Tracts' in result:
            tract_data = result['Census Tracts'][0]
            #print("All data:", tract_data).keys()  # Uncomment to see all available keys
            return tract_data['BASENAME']
        return "No Tract Found"
    except Exception as e:
        return f"Error: {e}"

# Using row 149 as an example:
lat, lon = 40.824783, -73.944216
tract_id = get_census_tract(lat, lon)

print(f"Census Tract: {tract_id}")

Census Tract: 231

In [19]:
# takes about 8-9 minutes to run
mta_data['Census Tract'] = mta_data.apply(lambda row: get_census_tract(row['GTFS Latitude'], row['GTFS Longitude']), axis=1)

In [20]:
mta_data['Census Tract Whole'] = mta_data['Census Tract'].str.split('.').str[0]

In [21]:
mta_data['Census Tract Whole'].sort_values()

464       1
401     100
209    1008
318     101
11      101
30      101
227     101
276     102
195     106
199    1072
163     109
136    1098
335      11
24       11
174      11
58      110
224     112
59      112
351    1124
352    1124
350    1126
468     113
10      113
226     113
317     113
6       114
482     114
400     114
131    1142
132    1144
0       115
186    1152
187    1166
88     1168
87     1174
86     1178
70      118
85     1182
162     119
371     119
469     119
27      119
238     119
188    1196
185    1198
90     1198
89     1198
83       12
399     120
223     120
189    1202
239     121
483     122
370     123
80      124
9       125
1       125
225     125
429     125
474     126
398     128
339     129
329      13
414      13
20       13
173      13
21       13
328      13
277     131
316     131
485     132
486     132
161     133
484     134
36      136
8       137
28      137
7       143
156     143
157     143
159     143
29      143
158     143
79      144
160     145
315     145
487     146
488     146
473     146
397     148
314     149
412      15
336      15
172      15
105      15
332      15
25       15
240     151
44     1522
270     153
271     155
472     156
396     158
340     159
430     159
313     159
428     161
40      161
395     166
312     167
241     169
489     170
490     170
272     171
394     172
311     175
341     177
460     179
231      18
101      18
233      18
102      18
459     181
176     181
64      182
393     182
310     183
441     186
155     189
281      19
461      19
462      19
274      19
463      19
63      190
440     190
309     191
219     195
308     195
392     196
218     197
388     197
154     197
291     197
491     198
177     199
82       20
363     200
439     200
307     205
365     206
279     208
152     209
327      21
477      21
171      21
476      21
170      21
235      21
331      21
306     211
342     213
140     213
71      214
280     216
258     216
385     217
151     217
153     218
425     220
426     220
60      220
387     221
305     223
424     224
217     225
492     226
493     226
386     227
138     227
178     227
438     228
304     229
216     229
377      23
290     231
150     231
149     231
437     232
148     235
215     235
436     236
256     236
213     237
257     238
222     238
383     239
61      240
303     241
384     243
289     243
220     243
147     243
278     246
179     247
446     248
494     248
495     248
73      248
221      25
62      250
72      250
302     251
146     251
458     253
457     253
74      254
269     255
288     259
81       26
456     261
268     261
455     263
145     263
362     266
361     266
267     267
454     267
180     269
301     269
375      27
266     271
144     273
452     277
300     277
65      278
143     281
294     283
295     283
299     283
453     283
293     285
97      285
142     287
96      287
66      288
95      289
104      29
141     293
298     293
67      296
181     297
475       3
68      300
360     300
183     301
182     301
297     303
139     305
69      306
252     308
296     309
19       31
374      31
5        31
411      31
353     319
343     319
445     326
41      327
354     329
273      33
169      33
326      33
292      33
422     336
344     337
423     338
118      34
338      35
39       35
444     350
57      350
345     351
56      354
253     354
232      36
54      360
427     361
55      362
184     367
92      369
325      37
337      37
324      37
421     378
448     383
259     383
214     383
78      386
376      39
26       39
420     392
94      397
93      397
251     398
84        4
77      400
382     401
449     401
212     403
381     403
130     405
91      405
450     405
419     408
380     409
129     409
175      41
103      41
211     413
250     414
417     418
379     419
418     422
210     423
113     423
76      426
16       43
378     431
112     431
75      432
416     434
249     438
127     439
111     439
190      44
126     443
248     446
125     447
410      45
18       45
409      45
247     450
124     453
255     460
246     462
443     462
451     465
254     468
17       47
265     473
117      48
368      48
245     480
442     484
244     486
168      49
98      491
123     493
122     495
243     496
121     497
334       5
479      50
242     504
43      506
287     507
435      51
390      51
391      51
286     511
120     513
285     513
14       52
406      52
45      520
46      520
99      529
100     529
4        53
47      532
48      532
38       54
369      54
191      54
110     549
408      55
230      55
50      552
119     553
128     555
13       56
284     569
407      57
15       57
283     575
228      58
51      580
52      586
109     589
3        59
478       6
234       6
37       60
53      606
116      61
108     613
107     613
115      63
389      63
2        63
434      65
35       68
405      68
404      68
264     683
236      69
263     693
106       7
282       7
333       7
465       7
413       7
367      70
167      71
322      71
166      71
262     713
366      72
323      73
261     739
403      74
34       74
433      75
33       76
12       76
49      768
260     769
237      77
359     786
432      79
42      798
466      80
32       80
355     804
229      81
321      81
165      81
356     820
357     826
114      83
373      83
358     830
467      84
31       84
372      85
192      86
196     864
431      87
447     871
197      88
198     884
347     894
22        9
330       9
415       9
23        9
346     900
133     908
320      91
164      91
134     910
349     910
348     916
402      92
135     920
202     938
203     938
193      94
470      94
200     942
201     942
319      95
204     954
364      96
481      96
194      96
480      96
205     972
206     972
137     974
275      98
471      99
207     992
208     998
Name: Census Tract Whole, dtype: object

## Note:
- Census Tracts are stringified numbers (must go back to put school data in same format)
- Decimals appear to break up densely populated areas into smaller Census Tracts

In [22]:
mta_data[mta_data['Census Tract Whole'].str.startswith('7')]

,GTFS Stop ID,Station ID,Complex ID,Division,Line,Stop Name,Borough,CBD,Daytime Routes,Structure,GTFS Latitude,GTFS Longitude,North Direction Label,South Direction Label,ADA,ADA Northbound,ADA Southbound,ADA Notes,Georeference,zip_code,Census Tract,Census Tract Whole
12,R18,13,13,BMT,Broadway - Brighton,28 St,M,True,R W,Subway,40.745494,-73.988691,Uptown,Downtown,0,0,0,NaN,POINT (-73.988691 40.745494),10119,76,76
33,R40,34,34,BMT,4th Av,53 St,Bk,False,R,Subway,40.645069,-74.014034,Manhattan,Southbound,0,0,0,NaN,POINT (-74.014034 40.645069),11220,76,76
34,R41,35,35,BMT,4th Av,59 St,Bk,False,N R,Subway,40.641362,-74.017881,Manhattan,Southbound,1,1,1,NaN,POINT (-74.017881 40.641362),11220,74,74
42,D27,43,43,BMT,Broadway - Brighton,Parkside Av,Bk,False,Q,Open Cut,40.655292,-73.961495,Manhattan,Southbound,0,0,0,NaN,POINT (-73.961495 40.655292),11226,798.02,798
49,D34,50,50,BMT,Broadway - Brighton,Avenue M,Bk,False,Q,Open Cut,40.617618,-73.959399,Manhattan,Southbound,0,0,0,NaN,POINT (-73.959399 40.617618),11230,768,768
106,M23,107,107,BMT,Jamaica,Broad St,M,True,J Z,Subway,40.706476,-74.011056,Brooklyn,Last Stop,0,0,0,NaN,POINT (-74.011056 40.706476),10271,7,7
166,A32,167,167,IND,8th Av - Fulton St,W 4 St-Wash Sq,M,True,A C E,Subway,40.732338,-74.000495,Uptown,Downtown,1,1,1,NaN,POINT (-74.000495 40.732338),10014,71,71
167,D20,167,167,IND,6th Av - Culver,W 4 St-Wash Sq,M,True,B D F M,Subway,40.732338,-74.000495,Uptown,Downtown,1,1,1,NaN,POINT (-74.000495 40.732338),10014,71,71
237,F21,237,237,IND,6th Av - Culver,Carroll St,Bk,False,F G,Subway,40.680303,-73.995048,Northbound,Southbound,0,0,0,NaN,POINT (-73.995048 40.680303),11231,77,77
260,F07,260,260,IND,Queens Blvd,75 Av,Q,False,E F,Subway,40.718331,-73.837324,Jamaica,Manhattan,0,0,0,NaN,POINT (-73.837324 40.718331),11375,769.01,769
261,G08,261,261,IND,Queens Blvd,Forest Hills-71 Av,Q,False,E F M R,Subway,40.721691,-73.844521,Outbound,Manhattan,1,1,1,NaN,POINT (-73.844521 40.721691),11375,739,739
262,G09,262,262,IND,Queens Blvd,67 Av,Q,False,M R,Subway,40.726523,-73.852719,Outbound,Manhattan,0,0,0,NaN,POINT (-73.852719 40.726523),11374,713.06,713
282,G24,282,282,IND,Crosstown,21 St,Q,False,G,Subway,40.744065,-73.949724,Court Square,Brooklyn,0,0,0,NaN,POINT (-73.949724 40.744065),11109,7.01,7
322,132,322,601,IRT,Broadway - 7Av,14 St,M,True,1 2 3,Subway,40.737826,-74.000201,Uptown,Downtown,1,1,1,NaN,POINT (-74.000201 40.737826),10011,71,71
323,133,323,323,IRT,Broadway - 7Av,Christopher St-Stonewall,M,True,1,Subway,40.733422,-74.002906,Uptown,Downtown,0,0,0,NaN,POINT (-74.002906 40.733422),10014,73,73
333,230,333,333,IRT,Clark St,Wall St,M,True,2 3,Subway,40.706821,-74.009100,Uptown,Brooklyn,0,0,0,NaN,POINT (-74.0091 40.706821),10005,7,7
359,247,359,359,IRT,Nostrand,Flatbush Av-Brooklyn College,Bk,False,2 5,Subway,40.632836,-73.947642,Manhattan,Last Stop,1,1,1,NaN,POINT (-73.947642 40.632836),11210,786.01,786
366,608,366,366,IRT,Pelham,Parkchester,Bx,False,6,Elevated,40.833226,-73.860816,Northbound,Manhattan,0,0,0,NaN,POINT (-73.860816 40.833226),10472,72,72
367,609,367,367,IRT,Pelham,St Lawrence Av,Bx,False,6,Elevated,40.831509,-73.867618,Northbound,Manhattan,0,0,0,NaN,POINT (-73.867618 40.831509),10472,70,70
403,632,403,403,IRT,Lexington Av,33 St,M,True,6,Subway,40.746081,-73.982076,Uptown,Downtown,0,0,0,NaN,POINT (-73.982076 40.746081),10016,74,74
413,419,413,413,IRT,Lexington Av,Wall St,M,True,4 5,Subway,40.707557,-74.011862,Uptown,Downtown,0,0,0,NaN,POINT (-74.011862 40.707557),10271,7,7
432,219,432,432,IRT,Lenox - White Plains Rd,Prospect Av,Bx,False,2 5,Elevated,40.819585,-73.901770,Northbound,Manhattan,0,0,0,NaN,POINT (-73.90177 40.819585),10455,79,79
433,220,433,433,IRT,Lenox - White Plains Rd,Jackson Av,Bx,False,2 5,Elevated,40.816490,-73.907807,Northbound,Manhattan,0,0,0,NaN,POINT (-73.907807 40.81649),10455,75,75
465,721,464,464,IRT,Flushing,Vernon Blvd-Jackson Av,Q,False,7,Subway,40.742626,-73.953581,Outbound,Manhattan,0,0,0,NaN,POINT (-73.953581 40.742626),11109,7.01,7

In [23]:
mta_data.head()

,GTFS Stop ID,Station ID,Complex ID,Division,Line,Stop Name,Borough,CBD,Daytime Routes,Structure,GTFS Latitude,GTFS Longitude,North Direction Label,South Direction Label,ADA,ADA Northbound,ADA Southbound,ADA Notes,Georeference,zip_code,Census Tract,Census Tract Whole
0,R01,1,1,BMT,Astoria,Astoria-Ditmars Blvd,Q,False,N W,Elevated,40.775036,-73.912034,Last Stop,Manhattan,0,0,0,NaN,POINT (-73.912034 40.775036),11105,115,115
1,R03,2,2,BMT,Astoria,Astoria Blvd,Q,False,N W,Elevated,40.770258,-73.917843,Astoria,Manhattan,1,1,1,NaN,POINT (-73.917843 40.770258),11102,125,125
2,R04,3,3,BMT,Astoria,30 Av,Q,False,N W,Elevated,40.766779,-73.921479,Astoria,Manhattan,0,0,0,NaN,POINT (-73.921479 40.766779),11102,63,63
3,R05,4,4,BMT,Astoria,Broadway,Q,False,N W,Elevated,40.761820,-73.925508,Astoria,Manhattan,0,0,0,NaN,POINT (-73.925508 40.76182),11106,59,59
4,R06,5,5,BMT,Astoria,36 Av,Q,False,N W,Elevated,40.756804,-73.929575,Astoria,Manhattan,0,0,0,NaN,POINT (-73.929575 40.756804),11106,53,53

In [27]:
mta_data_dropped = mta_data[['Daytime Routes', 'GTFS Stop ID', 'Station ID', 'Stop Name', 'Borough', 'GTFS Latitude', 'GTFS Longitude', 'Census Tract', 'Census Tract Whole', 'zip_code']]

In [28]:
mta_data_dropped.sample(10)

,Daytime Routes,GTFS Stop ID,Station ID,Stop Name,Borough,GTFS Latitude,GTFS Longitude,Census Tract,Census Tract Whole,zip_code
64,D,B18,65,79 St,Bk,40.613501,-74.000610,182,182,11228
122,L,L12,123,Grand St,Bk,40.711926,-73.940670,495,495,11211
437,3,302,437,145 St,M,40.820421,-73.936245,232,232,10039
306,1,116,306,125 St,M,40.815581,-73.958372,211,211,10027
448,7,702,448,Mets-Willets Point,Q,40.754622,-73.845625,383.02,383,11368
363,6,604,363,Westchester Sq-E Tremont Av,Bx,40.839892,-73.842952,200,200,10461
165,A C E,A31,166,14 St,M,40.740893,-74.001690,81,81,10011
385,4,410,385,176 St,Bx,40.848480,-73.911794,217,217,10453
171,E,E01,171,World Trade Center,M,40.712582,-74.009781,21,21,10279
158,C B,A21,159,81 St-Museum of Natural History,M,40.781433,-73.972143,143,143,10024

In [30]:
mta_data_dropped.to_csv('../cleaned_data/MTA_Subway_Stations_w_Tracts+Zip_2025.csv', index=False)