# MTA On-Time Performance EDA

## Data Dictionary:
- https://data.ny.gov/Transportation/MTA-Subway-Terminal-On-Time-Performance-2015-2019/f6rf-2a3t/about_data
- https://data.ny.gov/Transportation/MTA-Subway-Terminal-On-Time-Performance-2020-2024/vtvh-gimj/about_data

In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

mta_time_1 = pd.read_csv('../data/MTA_Subway_Terminal_On-Time_Performance_2015-2019.csv', low_memory=False)
mta_time_2 = pd.read_csv('../data/MTA_Subway_Terminal_On-Time_Performance_2020-2024.csv', low_memory=False)

mta_time_1.sample(5)

,month,division,line,day_type,num_on_time_trips,num_sched_trips,terminal_on_time_performance
1208,2019-04-01,B DIVISION,A,2,"1,985","2,488",79.7829582%
1117,2018-12-01,B DIVISION,N,1,"5,767","9,203",62.6643486%
560,2017-01-01,A DIVISION,7,1,"10,074","13,126",76.7484382%
1060,2018-10-01,A DIVISION,S 42nd,1,"14,278","14,370",99.3597773%
68,2015-03-01,B DIVISION,S Rock,1,"3,530","3,701",95.3796271%

In [2]:
mta_time_1[mta_time_1['line'] == 'J'].head()

Empty DataFrame
Columns: [month, division, line, day_type, num_on_time_trips, num_sched_trips, terminal_on_time_performance]
Index: []

In [3]:
mta_time_1['line'].value_counts()

line
1         69
2         69
S Rock    69
S Fkln    69
R         69
Q         69
N         69
M         69
L         69
JZ        69
G         69
F         69
E         69
D         69
C         69
A         69
S 42nd    69
7         69
6         69
5         69
4         69
3         69
B         60
W         18
Name: count, dtype: int64

In [4]:
mta_time_2.sample(5)

,month,division,line,day_type,num_on_time_trips,num_sched_trips,terminal_on_time_performance
1891,2021-06-01,A DIVISION,1,2,"1,915","2,336",81.977737%
2064,2021-03-01,B DIVISION,N,2,"1,486","1,722",86.29501%
1816,2021-08-01,B DIVISION,B,1,"3,236","4,312",75.046384%
2663,2020-01-01,B DIVISION,E,1,"7,165","8,898",80.52371%
1719,2021-10-01,A DIVISION,5,2,"1,206","1,402",86.01997%

In [5]:
mta_time_2['line'].value_counts()

line
1         120
D         120
R         120
Q         120
N         120
M         120
L         120
2         120
F         120
E         120
G         120
7         120
6         120
5         120
4         120
3         120
A         119
C         118
FS        112
H         112
J         112
GS        103
B          58
JZ          8
S 42nd      8
S Fkln      8
S Rock      8
Name: count, dtype: int64

In [6]:
mta_time_2[mta_time_2['line'] == 'JZ'].head()

,month,division,line,day_type,num_on_time_trips,num_sched_trips,terminal_on_time_performance
27,2024-12-01,B DIVISION,JZ,2,"2,242","2,432",92.1875%
28,2024-12-01,B DIVISION,JZ,1,"5,265","6,251",84.226525%
72,2024-11-01,B DIVISION,JZ,1,"4,767","5,984",79.66243%
73,2024-11-01,B DIVISION,JZ,2,"2,220","2,460",90.2439%
117,2024-10-01,B DIVISION,JZ,2,"1,416","1,528",92.670155%

In [7]:
mta_time_2[mta_time_2['line'] == 'J'].head()

,month,division,line,day_type,num_on_time_trips,num_sched_trips,terminal_on_time_performance
213,2024-08-01,B DIVISION,J,1,"5,348","6,582",81.2519%
214,2024-08-01,B DIVISION,J,2,"1,975","2,132",92.636025%
258,2024-07-01,B DIVISION,J,2,"2,011","2,228",90.26032%
259,2024-07-01,B DIVISION,J,1,"4,963","6,281",79.01608%
303,2024-06-01,B DIVISION,J,1,"4,722","5,582",84.59334%

In [8]:
mta_time_1.shape

(1596, 7)

In [9]:
mta_time_2.shape

(2686, 7)

In [10]:
mta_time_1[10:20]

,month,division,line,day_type,num_on_time_trips,num_sched_trips,terminal_on_time_performance
10,2015-01-01,B DIVISION,C,1,"3,359","4,000",83.975%
11,2015-01-01,B DIVISION,D,1,"4,022","5,288",76.0590015%
12,2015-01-01,B DIVISION,E,1,"5,453","7,894",69.0777806%
13,2015-01-01,B DIVISION,F,1,"4,597","7,939",57.9040181%
14,2015-01-01,B DIVISION,G,1,"3,961","5,664",69.9329096%
15,2015-01-01,B DIVISION,JZ,1,"4,374","5,444",80.3453343%
16,2015-01-01,B DIVISION,L,1,"9,109","9,808",92.8731648%
17,2015-01-01,B DIVISION,M,1,"3,761","5,315",70.7619944%
18,2015-01-01,B DIVISION,N,1,"3,601","5,259",68.4730937%
19,2015-01-01,B DIVISION,Q,1,"3,737","5,348",69.8765894%

# Note:
- From 2015-2019 (mta_time_1) there is no J line distinction, only JZ
- From 2020 onward (mta_time_2) there ARE line distinctions: J and JZ lines
- FS and GS line distinction are also introduced in 2020
- ALSO, H line introduced in 2020 (H = legacy label for 'Rockaway Park Shuttle')

## Converting S Fkln -> FS and S 42nd to GS:
- And S Rock -> RS
- And H -> RS

In [11]:
mta_time_1['line'] = mta_time_1['line'].apply(lambda line: 'FS' if line == 'S Fkln' else 'GS' if line == 'S 42nd' else 'RS' if line == 'S Rock' else line)
mta_time_2['line'] = mta_time_2['line'].apply(lambda line: 'FS' if line == 'S Fkln' else 'GS' if line == 'S 42nd' else 'RS' if (line == 'S Rock' or line == 'H') else line)

In [12]:
# Combining the two datasets:
mta_time_df = pd.concat([mta_time_1, mta_time_2], ignore_index=True)

mta_time_df.shape

(4282, 7)

In [13]:
mta_time_df.sample(10)

,month,division,line,day_type,num_on_time_trips,num_sched_trips,terminal_on_time_performance
4182,2020-03-01,B DIVISION,L,1,"6,895","7,554",91.276145%
616,2017-03-01,B DIVISION,G,1,"4,501","6,136",73.3539765%
3137,2022-02-01,A DIVISION,6,2,"2,085","2,676",77.9148%
1227,2019-04-01,B DIVISION,N,2,"1,229","1,692",72.6359338%
484,2016-10-01,A DIVISION,2,1,"2,587","7,150",36.1818182%
1819,2024-08-01,B DIVISION,R,1,"5,039","6,638",75.91142%
1396,2019-08-01,B DIVISION,F,1,"5,323","8,622",61.7374159%
2968,2022-06-01,B DIVISION,E,1,"6,472","9,020",71.75166%
742,2017-08-01,B DIVISION,R,1,"4,682","6,528",71.7218137%
3347,2021-10-01,B DIVISION,Q,1,"5,003","6,615",75.63114%

In [14]:
mta_time_df['line'].value_counts(sort=False)

line
1     189
2     189
3     189
4     189
5     189
6     189
7     189
GS    180
A     188
B     118
C     187
D     189
E     189
F     189
G     189
JZ     77
L     189
M     189
N     189
Q     189
R     189
FS    189
RS    189
W      18
J     112
Name: count, dtype: int64

In [15]:
len(mta_time_df['line'].unique())

25

In [16]:
JZ_df = mta_time_df[mta_time_df['line'] == 'JZ']
J_df = mta_time_df[mta_time_df['line'] == 'J']

JZ_df.head()

,month,division,line,day_type,num_on_time_trips,num_sched_trips,terminal_on_time_performance
15,2015-01-01,B DIVISION,JZ,1,"4,374","5,444",80.3453343%
38,2015-02-01,B DIVISION,JZ,1,"3,750","5,193",72.2125939%
61,2015-03-01,B DIVISION,JZ,1,"4,816","5,996",80.3202135%
84,2015-04-01,B DIVISION,JZ,1,"4,770","5,998",79.5265088%
107,2015-05-01,B DIVISION,JZ,1,"3,935","5,454",72.1488816%

In [17]:
J_df.head()

,month,division,line,day_type,num_on_time_trips,num_sched_trips,terminal_on_time_performance
1809,2024-08-01,B DIVISION,J,1,"5,348","6,582",81.2519%
1810,2024-08-01,B DIVISION,J,2,"1,975","2,132",92.636025%
1854,2024-07-01,B DIVISION,J,2,"2,011","2,228",90.26032%
1855,2024-07-01,B DIVISION,J,1,"4,963","6,281",79.01608%
1899,2024-06-01,B DIVISION,J,1,"4,722","5,582",84.59334%

In [18]:
JZ_df.describe()

        day_type
count  77.000000
mean    1.168831
std     0.377059
min     1.000000
25%     1.000000
50%     1.000000
75%     1.000000
max     2.000000

In [19]:
J_df.describe()

         day_type
count  112.000000
mean     1.500000
std      0.502247
min      1.000000
25%      1.000000
50%      1.500000
75%      2.000000
max      2.000000

## Converting numerical data into datetimes, ints, and floats:

In [20]:
mta_time_df.dtypes

month                           object
division                        object
line                            object
day_type                         int64
num_on_time_trips               object
num_sched_trips                 object
terminal_on_time_performance    object
dtype: object

In [21]:
# Datetime conversion:
mta_time_df['month'] = pd.to_datetime(mta_time_df['month'], format='%Y-%m-%d')

In [22]:
# Int conversion:
mta_time_df['num_on_time_trips'] = mta_time_df['num_on_time_trips'].apply(lambda x: int(x.replace(',', '')))
mta_time_df['num_sched_trips'] = mta_time_df['num_sched_trips'].apply(lambda x: int(x.replace(',', '')))

In [23]:
# Float conversion:
mta_time_df['terminal_on_time_performance'] = mta_time_df['terminal_on_time_performance'].apply(lambda x: float(x.replace('%', '')))

In [24]:
mta_time_df.head()

,month,division,line,day_type,num_on_time_trips,num_sched_trips,terminal_on_time_performance
0,2015-01-01,A DIVISION,1,1,6874,9017,76.233781
1,2015-01-01,A DIVISION,2,1,2920,6175,47.287449
2,2015-01-01,A DIVISION,3,1,4004,5834,68.632156
3,2015-01-01,A DIVISION,4,1,3692,7623,48.432376
4,2015-01-01,A DIVISION,5,1,3203,6491,49.345247

In [25]:
mta_time_df.dtypes

month                           datetime64[ns]
division                                object
line                                    object
day_type                                 int64
num_on_time_trips                        int64
num_sched_trips                          int64
terminal_on_time_performance           float64
dtype: object

## Creating 'Daytime Routes' column, changing JZ -> Z line data
- NO exclusively J data between 2015 and 2019!

In [26]:
mta_time_df['Daytime Routes'] = mta_time_df['line'].apply(lambda line: 'Z' if line == 'JZ' else line)

mta_time_df.sample(10)

,month,division,line,day_type,num_on_time_trips,num_sched_trips,terminal_on_time_performance,Daytime Routes
2162,2023-12-01,B DIVISION,FS,1,4676,4708,99.320304,FS
2872,2022-08-01,B DIVISION,B,1,3456,4462,77.454054,B
222,2015-10-01,B DIVISION,JZ,1,3972,6010,66.089850,Z
1897,2024-06-01,B DIVISION,RS,1,3245,3360,96.577380,RS
207,2015-10-01,A DIVISION,1,1,7194,9932,72.432541,1
2633,2023-01-01,A DIVISION,2,1,5415,6811,79.503745,2
89,2015-04-01,B DIVISION,R,1,3759,6248,60.163252,R
1167,2019-02-01,B DIVISION,RS,1,3108,3193,97.337927,RS
1828,2024-07-01,A DIVISION,4,2,1748,2416,72.350990,4
1971,2024-04-01,B DIVISION,A,2,1900,2388,79.564490,A

In [27]:
mta_time_df.to_json('../cleaned_data/MTA_Subway_Performance.json', orient='index')