# MTA On-Time Performance EDA

## Data Dictionary:
- https://data.ny.gov/Transportation/MTA-Subway-Terminal-On-Time-Performance-2015-2019/f6rf-2a3t/about_data
- https://data.ny.gov/Transportation/MTA-Subway-Terminal-On-Time-Performance-2020-2024/vtvh-gimj/about_data

In [29]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

mta_time_1 = pd.read_csv('../data/MTA_Subway_Terminal_On-Time_Performance_2015-2019.csv', low_memory=False)
mta_time_2 = pd.read_csv('../data/MTA_Subway_Terminal_On-Time_Performance_2020-2024.csv', low_memory=False)

mta_time_1.head()

,month,division,line,day_type,num_on_time_trips,num_sched_trips,terminal_on_time_performance
0,2015-01-01,A DIVISION,1,1,"6,874","9,017",76.2337806%
1,2015-01-01,A DIVISION,2,1,"2,920","6,175",47.2874494%
2,2015-01-01,A DIVISION,3,1,"4,004","5,834",68.6321563%
3,2015-01-01,A DIVISION,4,1,"3,692","7,623",48.4323757%
4,2015-01-01,A DIVISION,5,1,"3,203","6,491",49.3452473%

In [30]:
mta_time_2.head()

,month,division,line,day_type,num_on_time_trips,num_sched_trips,terminal_on_time_performance
0,2024-12-01,A DIVISION,1,1,"7,689","9,711",79.17825%
1,2024-12-01,A DIVISION,1,2,"2,907","3,240",89.72222%
2,2024-12-01,A DIVISION,2,1,"4,693","6,997",67.071605%
3,2024-12-01,A DIVISION,2,2,"1,772","2,690",65.873605%
4,2024-12-01,A DIVISION,3,2,"1,389","1,710",81.22807%

In [31]:
mta_time_1.shape

(1596, 7)

In [32]:
mta_time_2.shape

(2686, 7)

In [33]:
mta_time_1[10:20]

,month,division,line,day_type,num_on_time_trips,num_sched_trips,terminal_on_time_performance
10,2015-01-01,B DIVISION,C,1,"3,359","4,000",83.975%
11,2015-01-01,B DIVISION,D,1,"4,022","5,288",76.0590015%
12,2015-01-01,B DIVISION,E,1,"5,453","7,894",69.0777806%
13,2015-01-01,B DIVISION,F,1,"4,597","7,939",57.9040181%
14,2015-01-01,B DIVISION,G,1,"3,961","5,664",69.9329096%
15,2015-01-01,B DIVISION,JZ,1,"4,374","5,444",80.3453343%
16,2015-01-01,B DIVISION,L,1,"9,109","9,808",92.8731648%
17,2015-01-01,B DIVISION,M,1,"3,761","5,315",70.7619944%
18,2015-01-01,B DIVISION,N,1,"3,601","5,259",68.4730937%
19,2015-01-01,B DIVISION,Q,1,"3,737","5,348",69.8765894%

In [34]:
mta_time_df = pd.concat([mta_time_1, mta_time_2], ignore_index=True)

mta_time_df.shape

(4282, 7)

In [35]:
mta_time_df.sample(10)

,month,division,line,day_type,num_on_time_trips,num_sched_trips,terminal_on_time_performance
836,2017-12-01,B DIVISION,N,1,"3,642","5,710",63.7828371%
966,2018-06-01,A DIVISION,6,1,"7,105","11,728",60.5815143%
1285,2019-06-01,A DIVISION,3,1,"4,831","5,896",81.9369064%
4203,2020-02-01,A DIVISION,6,2,"2,555","2,860",89.33566%
3618,2021-04-01,B DIVISION,Q,2,"1,924","2,176",88.419116%
852,2018-01-01,B DIVISION,C,1,"2,990","8,612",34.7189967%
3547,2021-05-01,B DIVISION,B,1,"3,056","3,872",78.92562%
2507,2023-04-01,A DIVISION,6,2,"2,231","2,820",79.11348%
541,2016-12-01,B DIVISION,D,1,"3,341","5,620",59.4483986%
2086,2024-02-01,B DIVISION,N,2,"1,217","1,944",62.602884%

In [36]:
mta_time_df['line'].value_counts(sort=False)

line
1         189
2         189
3         189
4         189
5         189
6         189
7         189
S 42nd     77
A         188
B         118
C         187
D         189
E         189
F         189
G         189
JZ         77
L         189
M         189
N         189
Q         189
R         189
S Fkln     77
S Rock     77
W          18
FS        112
GS        103
H         112
J         112
Name: count, dtype: int64

In [37]:
len(mta_time_df['line'].unique())

28

In [40]:
FS_df = mta_time_df[mta_time_df['line'] == 'FS']
SFkln_df = mta_time_df[mta_time_df['line'] == 'S Fkln']

# If you have a specific column to match (e.g., station names)
intersect_FS = pd.merge(FS_df, SFkln_df, on='num_sched_trips', how='inner')
intersect_FS.head()

,month_x,division_x,line_x,day_type_x,num_on_time_trips_x,num_sched_trips,terminal_on_time_performance_x,month_y,division_y,line_y,day_type_y,num_on_time_trips_y,terminal_on_time_performance_y
0,2024-05-01,B DIVISION,FS,1,"5,173","5,192",99.63405%,2018-05-01,B DIVISION,S Fkln,1,"5,169",99.5570108%
1,2024-05-01,B DIVISION,FS,1,"5,173","5,192",99.63405%,2019-01-01,B DIVISION,S Fkln,1,"5,161",99.4029276%
2,2024-05-01,B DIVISION,FS,1,"5,173","5,192",99.63405%,2019-04-01,B DIVISION,S Fkln,1,"5,184",99.8459168%
3,2024-05-01,B DIVISION,FS,1,"5,173","5,192",99.63405%,2019-08-01,B DIVISION,S Fkln,1,"5,175",99.6725732%
4,2024-04-01,B DIVISION,FS,2,"1,688","1,696",99.5283%,2019-04-01,B DIVISION,S Fkln,2,"1,682",99.1745283%

In [46]:
JZ_df = mta_time_df[mta_time_df['line'] == 'JZ']
J_df = mta_time_df[mta_time_df['line'] == 'J']

JZ_df.head()

,month,division,line,day_type,num_on_time_trips,num_sched_trips,terminal_on_time_performance
15,2015-01-01,B DIVISION,JZ,1,"4,374","5,444",80.3453343%
38,2015-02-01,B DIVISION,JZ,1,"3,750","5,193",72.2125939%
61,2015-03-01,B DIVISION,JZ,1,"4,816","5,996",80.3202135%
84,2015-04-01,B DIVISION,JZ,1,"4,770","5,998",79.5265088%
107,2015-05-01,B DIVISION,JZ,1,"3,935","5,454",72.1488816%

In [47]:
J_df.head()

,month,division,line,day_type,num_on_time_trips,num_sched_trips,terminal_on_time_performance
1809,2024-08-01,B DIVISION,J,1,"5,348","6,582",81.2519%
1810,2024-08-01,B DIVISION,J,2,"1,975","2,132",92.636025%
1854,2024-07-01,B DIVISION,J,2,"2,011","2,228",90.26032%
1855,2024-07-01,B DIVISION,J,1,"4,963","6,281",79.01608%
1899,2024-06-01,B DIVISION,J,1,"4,722","5,582",84.59334%