# MTA Subway Stations EDA

## Data Dictionary:
- https://data.ny.gov/Transportation/MTA-Subway-Stations/39hk-dx4f/about_data

In [2]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

mta_data = pd.read_csv('../data/MTA_Subway_Stations_2025.csv', low_memory=False)

mta_data[150:175]

,GTFS Stop ID,Station ID,Complex ID,Division,Line,Stop Name,Borough,CBD,Daytime Routes,Structure,GTFS Latitude,GTFS Longitude,North Direction Label,South Direction Label,ADA,ADA Northbound,ADA Southbound,ADA Notes,Georeference
150,D13,151,151,IND,Concourse,145 St,M,False,B D,Subway,40.824783,-73.944216,Uptown,Downtown,0,0,0,NaN,POINT (-73.944216 40.824783)
151,A14,152,152,IND,8th Av - Fulton St,135 St,M,False,C B,Subway,40.817894,-73.947649,Uptown,Downtown,0,0,0,NaN,POINT (-73.947649 40.817894)
152,A15,153,153,IND,8th Av - Fulton St,125 St,M,False,A C B D,Subway,40.811109,-73.952343,Uptown,Downtown,1,1,1,NaN,POINT (-73.952343 40.811109)
153,A16,154,154,IND,8th Av - Fulton St,116 St,M,False,C B,Subway,40.805085,-73.954882,Uptown,Downtown,0,0,0,NaN,POINT (-73.954882 40.805085)
154,A17,155,155,IND,8th Av - Fulton St,Cathedral Pkwy (110 St),M,False,C B,Subway,40.800603,-73.958161,Uptown,Downtown,0,0,0,NaN,POINT (-73.958161 40.800603)
155,A18,156,156,IND,8th Av - Fulton St,103 St,M,False,C B,Subway,40.796092,-73.961454,Uptown,Downtown,0,0,0,NaN,POINT (-73.961454 40.796092)
156,A19,157,157,IND,8th Av - Fulton St,96 St,M,False,C B,Subway,40.791642,-73.964696,Uptown,Downtown,0,0,0,NaN,POINT (-73.964696 40.791642)
157,A20,158,158,IND,8th Av - Fulton St,86 St,M,False,C B,Subway,40.785868,-73.968916,Uptown,Downtown,0,0,0,NaN,POINT (-73.968916 40.785868)
158,A21,159,159,IND,8th Av - Fulton St,81 St-Museum of Natural History,M,False,C B,Subway,40.781433,-73.972143,Uptown,Downtown,0,0,0,NaN,POINT (-73.972143 40.781433)
159,A22,160,160,IND,8th Av - Fulton St,72 St,M,False,C B,Subway,40.775594,-73.976410,Uptown,Downtown,0,0,0,NaN,POINT (-73.97641 40.775594)
160,A24,161,614,IND,8th Av - Fulton St,59 St-Columbus Circle,M,True,A C B D,Subway,40.768296,-73.981736,Uptown,Downtown,1,1,1,NaN,POINT (-73.981736 40.768296)
161,A25,162,162,IND,8th Av - Fulton St,50 St,M,True,C E,Subway,40.762456,-73.985984,Uptown,Downtown,2,0,1,Downtown only,POINT (-73.985984 40.762456)
162,A27,163,611,IND,8th Av - Fulton St,42 St-Port Authority Bus Terminal,M,True,A C E,Subway,40.757308,-73.989735,Uptown,Downtown,1,1,1,NaN,POINT (-73.989735 40.757308)
163,A28,164,164,IND,8th Av - Fulton St,34 St-Penn Station,M,True,A C E,Subway,40.752287,-73.993391,Uptown,Downtown,1,1,1,NaN,POINT (-73.993391 40.752287)
164,A30,165,165,IND,8th Av - Fulton St,23 St,M,True,C E,Subway,40.745906,-73.998041,Uptown,Downtown,0,0,0,NaN,POINT (-73.998041 40.745906)
165,A31,166,618,IND,8th Av - Fulton St,14 St,M,True,A C E,Subway,40.740893,-74.001690,Uptown,Downtown,1,1,1,NaN,POINT (-74.00169 40.740893)
166,A32,167,167,IND,8th Av - Fulton St,W 4 St-Wash Sq,M,True,A C E,Subway,40.732338,-74.000495,Uptown,Downtown,1,1,1,NaN,POINT (-74.000495 40.732338)
167,D20,167,167,IND,6th Av - Culver,W 4 St-Wash Sq,M,True,B D F M,Subway,40.732338,-74.000495,Uptown,Downtown,1,1,1,NaN,POINT (-74.000495 40.732338)
168,A33,168,168,IND,8th Av - Fulton St,Spring St,M,True,C E,Subway,40.726227,-74.003739,Uptown,Downtown,2,0,1,Downtown only,POINT (-74.003739 40.726227)
169,A34,169,169,IND,8th Av - Fulton St,Canal St,M,True,A C E,Subway,40.720824,-74.005229,Uptown,Downtown,0,0,0,NaN,POINT (-74.005229 40.720824)
170,A36,170,624,IND,8th Av - Fulton St,Chambers St,M,True,A C,Subway,40.714111,-74.008585,Uptown,Brooklyn,0,0,0,NaN,POINT (-74.008585 40.714111)
171,E01,171,624,IND,8th Av - Fulton St,World Trade Center,M,True,E,Subway,40.712582,-74.009781,Uptown,Last Stop,1,1,1,NaN,POINT (-74.009781 40.712582)
172,A38,172,628,IND,8th Av - Fulton St,Fulton St,M,True,A C,Subway,40.710197,-74.007691,Uptown,Brooklyn,1,1,1,NaN,POINT (-74.007691 40.710197)
173,A40,173,173,IND,8th Av - Fulton St,High St,Bk,False,A C,Subway,40.699337,-73.990531,Manhattan,Outbound,0,0,0,NaN,POINT (-73.990531 40.699337)
174,A41,174,636,IND,8th Av - Fulton St,Jay St-MetroTech,Bk,False,A C F,Subway,40.692338,-73.987342,Manhattan,Outbound,1,1,1,NaN,POINT (-73.987342 40.692338)

In [3]:
mta_data.shape

(496, 19)

In [18]:
mta_data['GTFS Stop ID'].is_unique

True

In [16]:
mta_data['Station ID'].nunique()

493

## Note:
- three (3) duplicate Station ID numbers exist:
- 151, 167, 461

In [33]:
dup_ids_1 = mta_data[mta_data['Station ID'].duplicated(keep='last')]    # Get the first occurrences of duplicates ('last' duplicate is not considered a duplicate in this function call)
dup_ids_2 = mta_data[mta_data['Station ID'].duplicated(keep='first')]   # Get the last occurrences of duplicates ('first' duplicate is not considered a duplicate in this function call)

dup_ids_1

,GTFS Stop ID,Station ID,Complex ID,Division,Line,Stop Name,Borough,CBD,Daytime Routes,Structure,GTFS Latitude,GTFS Longitude,North Direction Label,South Direction Label,ADA,ADA Northbound,ADA Southbound,ADA Notes,Georeference
149,A12,151,151,IND,8th Av - Fulton St,145 St,M,False,A C,Subway,40.824783,-73.944216,Uptown,Downtown,0,0,0,NaN,POINT (-73.944216 40.824783)
166,A32,167,167,IND,8th Av - Fulton St,W 4 St-Wash Sq,M,True,A C E,Subway,40.732338,-74.000495,Uptown,Downtown,1,1,1,NaN,POINT (-74.000495 40.732338)
461,R09,461,461,BMT,Astoria,Queensboro Plaza,Q,False,N W,Elevated,40.750582,-73.940202,Astoria,Manhattan,1,1,1,NaN,POINT (-73.940202 40.750582)

In [34]:
dup_ids_2

,GTFS Stop ID,Station ID,Complex ID,Division,Line,Stop Name,Borough,CBD,Daytime Routes,Structure,GTFS Latitude,GTFS Longitude,North Direction Label,South Direction Label,ADA,ADA Northbound,ADA Southbound,ADA Notes,Georeference
150,D13,151,151,IND,Concourse,145 St,M,False,B D,Subway,40.824783,-73.944216,Uptown,Downtown,0,0,0,NaN,POINT (-73.944216 40.824783)
167,D20,167,167,IND,6th Av - Culver,W 4 St-Wash Sq,M,True,B D F M,Subway,40.732338,-74.000495,Uptown,Downtown,1,1,1,NaN,POINT (-74.000495 40.732338)
462,718,461,461,IRT,Flushing,Queensboro Plaza,Q,False,7,Elevated,40.750582,-73.940202,Outbound,Manhattan,1,1,1,NaN,POINT (-73.940202 40.750582)